### ISSUE TITLE
config['schemas_remote_master'] not pointing to raw files Github URL 

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-project#14]
In order to be able to load the yaml Schema files from Github the 
self.config['schemas_remote_master']  should be
'https://raw.githubusercontent.com/sonata-nfv/tng-schema/master' so that the tng-validation package can download the 5GATNGO descriptor Schema files to be used in the validation syntax. 
The current URL: "https://github.com/sonata-nfv/tng-schema" points to the HTML files.  

Thanks! Please, correct me if I didn't understand the use of this value.

**Comment by mpeuster** [comment]
Hi @antonroman 

Btw. we introduced a `descriptor_schema` field in each of the new 5GTANGO descriptors, e.g.,
https://github.com/sonata-nfv/tng-schema/blob/master/service-descriptor/examples/simplest-example.yml

This one points directly to the underlying schema for that particular descriptor. Maybe we should rely on these to download and use the schemas for the validator?

What do you think?

Example NSD:

```yaml
---
descriptor_schema: "https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/service-descriptor/nsd-schema.yml"

vendor: "eu.sonata-nfv.service-descriptor"
name: "simplest-example"
version: "0.2"
```
