### ISSUE TITLE
BUG: Paths in project.yml should be relative to project folder root

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-project#15]
Now we have:

```yaml
descriptor_extension: yml
files:
- path: test_project1/sources/vnfd/vnfd-sample.yml
  tags:
  - eu.5gtango
  type: application/vnd.5gtango.vnfd
- path: test_project1/sources/nsd/nsd-sample.yml
  tags:
  - eu.5gtango
  type: application/vnd.5gtango.nsd
package:
  description: Some description about this sample
  maintainer: Name, Company, Contact
  name: 5gtango-project-sample
  vendor: eu.5gtango
  version: '0.1'
version: '0.5'
```

but `test_project1` should not be part of the paths to the files. The paths need to be relative to the `project.yml` itself, not to the `PWD` in which `tng-project` was called.

Should be:

```yaml
descriptor_extension: yml
files:
- path: sources/vnfd/vnfd-sample.yml
  tags:
  - eu.5gtango
  type: application/vnd.5gtango.vnfd
- path: sources/nsd/nsd-sample.yml
  tags:
  - eu.5gtango
  type: application/vnd.5gtango.nsd
package:
  description: Some description about this sample
  maintainer: Name, Company, Contact
  name: 5gtango-project-sample
  vendor: eu.5gtango
  version: '0.1'
version: '0.5'
```
