### ISSUE TITLE
Support for testing tags in project manifest

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-project#81]
The project manifest may look like this if people (manually) add testing tags:

```yaml
...
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd”
    tags:
        - tag1
        - tag2
    testing_tags:
        - foo
```

Just have to test and ensure that 

* [x] the tool doesn't crash if these additional testing tags are included
* [x] it doesn't remove them at any point
